//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTime
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uh1294526_dbEntities : DbContext
    {
        public uh1294526_dbEntities()
            : base("name=uh1294526_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Playlists> Playlists { get; set; }
        public virtual DbSet<Singers> Singers { get; set; }
        public virtual DbSet<Tracks> Tracks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
