//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTime
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tracks()
        {
            this.Singers = new HashSet<Singers>();
            this.Tracks1 = new HashSet<Tracks>();
        }
    
        public int Track_ID { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int Album_ID { get; set; }
        public int TotalListens { get; set; }
        public bool Verification { get; set; }
        public Nullable<int> Track_Track_ID { get; set; }
        public Nullable<int> Playlist_Playlist_ID { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Playlists Playlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Singers> Singers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracks> Tracks1 { get; set; }
        public virtual Tracks Tracks2 { get; set; }
    }
}
